name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Docker Registry
      run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Set date-based tag
      id: vars
      run: echo "tag=$(date +%s)" >> "$GITHUB_OUTPUT"
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/iamangus/agentfile-email-bridge/agentfile-email-bridge:latest
    - name: Push the latest Docker image
      run: docker push docker.pkg.github.com/iamangus/agentfile-email-bridge/agentfile-email-bridge:latest
    - name: Retag with timestamp
      run: docker tag docker.pkg.github.com/iamangus/agentfile-email-bridge/agentfile-email-bridge:latest docker.pkg.github.com/iamangus/agentfile-email-bridge/agentfile-email-bridge:${{ steps.vars.outputs.tag }}
    - name: Push the tagged Docker image
      run: docker push docker.pkg.github.com/iamangus/agentfile-email-bridge/agentfile-email-bridge:${{ steps.vars.outputs.tag }}
